package gupsmile.com.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6146CB)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE6DEFF)
val md_theme_light_onPrimaryContainer = Color(0xFF1C0062)
val md_theme_light_secondary = Color(0xFF006A69)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF6FF7F5)
val md_theme_light_onSecondaryContainer = Color(0xFF002020)
val md_theme_light_tertiary = Color(0xFF5555A9)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE2DFFF)
val md_theme_light_onTertiaryContainer = Color(0xFF0E0664)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE6E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF48454E)
val md_theme_light_outline = Color(0xFF79757F)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFCABEFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6146CB)
val md_theme_light_outlineVariant = Color(0xFFC9C4D0)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_background_filter = Color(0xFFC0B3EA )

val md_theme_dark_primary = Color(0xFFCABEFF)
val md_theme_dark_onPrimary = Color(0xFF31009A)
val md_theme_dark_primaryContainer = Color(0xFF482AB2)
val md_theme_dark_onPrimaryContainer = Color(0xFFE6DEFF)
val md_theme_dark_secondary = Color(0xFF4DDAD9)
val md_theme_dark_onSecondary = Color(0xFF003736)
val md_theme_dark_secondaryContainer = Color(0xFF00504F)
val md_theme_dark_onSecondaryContainer = Color(0xFF6FF7F5)
val md_theme_dark_tertiary = Color(0xFFC2C1FF)
val md_theme_dark_onTertiary = Color(0xFF262477)
val md_theme_dark_tertiaryContainer = Color(0xFF3D3C8F)
val md_theme_dark_onTertiaryContainer = Color(0xFFE2DFFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1E)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1E)
val md_theme_dark_onSurface = Color(0xFFE6E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF48454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val md_theme_dark_inversePrimary = Color(0xFF6146CB)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFCABEFF)
val md_theme_dark_outlineVariant = Color(0xFF48454E)
val md_theme_dark_scrim = Color(0xFF000000)



val background_filter_ligth = Color(0xFFFFFFFF)
